### PR TITLE
added cvmfs_claim_ownership for the client configuration

### PR DESCRIPTION
**Pull request by mboisson**
I think I added the parameter correctly, but please check.

### CODE REVIEW

**Comment by mboisson** [comment]
I am not sure why one test failed, but I don't think it is linked to the changed contained in this PR.

**Comment by traylenator** [comment]
Indeed it's failing because puppet4 version of puppet-concat is stricter about it's input.
I'll need to fix that first.

**Comment by traylenator** [comment]
Genrally the patch looks fine - thanks.

It needs some tests I would say.
The previous merge request is almost identical example I would say. 
https://github.com/cvmfs/puppet-cvmfs/pull/61

**Comment by mboisson** [comment]
Yeah.... I figured you'ld say it needs some tests. I'm lost in puppet language, test-wise however.

**Comment by mboisson** [comment]
Ok, I tried to copy what seemed to be tests, and adapt them for the new parameter.

**Comment by mboisson** [comment]
Ok, it seems like all tests pass except the one which fails due to reasons unrelated to this PR.

**Comment by traylenator** [comment]
Hi @mboisson thanks for the extra tests.

I fixed up the tests - trivial.

If you can rebase and squash your commits then we are good to go with this.

**Comment by mboisson** [comment]
Nevermind, figured it out.

**Comment by traylenator** [comment]
Thanks, I'll make a new release in next day or two.

**Pull request merged**
